### ISSUE TITLE
Price Overlay not showing entries

### ISSUE THREAD

**Issue by SydneyKereliuk** [kalilistic/ACT.Kapture#50]
Kapture logs show entries, price log still says "waiting for loot..."

Following error in ACT may be related:
```
***** 2021-02-12T15:08:58 - Notification
Event Handler Unhandled Exceptions
In the last minute, these plugins caused exceptions in event handlers:

Aetherbridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null [3 time(s)]
```

**Comment by SydneyKereliuk** [comment]
Restart of ACT solved issue.

**Comment by SydneyKereliuk** [comment]
The Aetherbridge issue is actually persisting.

**Comment by kalilistic** [comment]
Hey, sorry for the slow response. I've just released an update with the game data which would've caused problems on new items. This could also happen if Universalis (where Kapture gets market data) is down. If Kapture price isn't working, can check to see if https://universalis.app/ is up. I'll look at adding a more friendly warning message in a future release.

**Comment by kalilistic** [comment]
Going to close this but feel free to reopen or create a new issue if it's still happening.
